const socketMessage = {
    COMMUNITY_CHAT:"COMMUNITY_CHAT",
    USER_CONNECTED:"USER_CONNECTED",
    MESSAGE_REVIEVED:"MESSAGE_REVIEVED",
    MESSAGE_SENT:"MESSAGE_SENT",
    USER_DISCONNECTED:"USER_DISCONNECTED",
    TYPING:"TYPING",
    VERIFY_USER:"VERIFY_USER",
    LOGOUT:"LOGOUT"
};
export default socketMessage;
